Vagrant.configure(2) do |config|
  config.vm.box = "centos-6.6_x86_64"
  
  # config.vm.hostname = "devops-02"
 
   # config.vm.network "forwarded_port", guest: 8000, host: 8000
   # config.vm.network "forwarded_port", guest: 5000, host: 5000
 
  # config.vm.provider "virtualbox" do |vb|
  #     vb.memory = "2048"
  #     vb.cpus = 2
  # end

  # vagrant up
  config.vm.define :default do |default_config|
    default_config.vm.hostname = "reboot-devops-02"
    default_config.vm.network :private_network, ip: "192.168.99.10"
    default_config.vm.network :forwarded_port, guest: 8000, host: 8000
    default_config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # vagrant up webserver_01
  config.vm.define :webserver_01 do |webserver_01_config|
    webserver_01_config.vm.hostname = "reboot-ms-web-01"
    webserver_01_config.vm.network "private_network", ip: "192.168.99.11"

    webserver_01_config.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
      vb.cpus = 1
    end
  end

  # vagrant up webserver_02
  config.vm.define :webserver_02 do |webserver_02_config|
    webserver_02_config.vm.hostname = "reboot-ms-web-02"
    webserver_02_config.vm.network "private_network", ip: "192.168.99.12"

    webserver_02_config.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
      vb.cpus = 1
    end
  end

  # vagrant up webserver_03
  config.vm.define :webserver_03 do |webserver_03_config|
    webserver_03_config.vm.hostname = "reboot-ms-web-01"
    webserver_03_config.vm.network "private_network", ip: "192.168.99.13"
    webserver_03_config.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
      vb.cpus = 1
    end
  end

  # vagrant up zabbix_server
  config.vm.define :zabbix_server do |zabbix_server_config|
    zabbix_server_config.vm.hostname = "zabbix-server-1"
    zabbix_server_config.vm.network :private_network, ip: "192.168.99.14"
    zabbix_server_config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  # vagrant up elk
  config.vm.define :elk_server do |elk_server_config|
    elk_server_config.vm.hostname = "elk-server-1"
    elk_server_config.vm.network :private_network, ip: "192.168.99.15"
    elk_server_config.vm.provider "virtualbox" do |vb|
      vb.memory = "3000"
      vb.cpus = 2
    end
  end


end
