Vagrant.configure(2) do |config|
  config.vm.box = "centos-6.6-x86_64"
  
  #config.vm.network "forwarded_port", guest: 8000, host: 8000
  #config.vm.hostname = "reboot-devops-02"
  #config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "2048"
#	 vb.cpus = 2
#  end
  
	config.vm.define :default do |default_config|
		default_config.vm.hostname = "reboot-devops-02"
		default_config.vm.network :private_network, ip: "192.168.99.10"
		default_config.vm.network :forwarded_port, guest: 8000, host: 8000
		default_config.vm.provider "virtualbox" do |vb|
			vb.memory = "2048"
			vb.cpus = 2
		end
	end
	
	config.vm.define :webserver_01 do |webserver_01_config|
		webserver_01_config.vm.hostname = "reboot-ms-web-01"
		webserver_01_config.vm.network :private_network, ip: "192.168.99.11"
		webserver_01_config.vm.provider "virtualbox" do |vb|
			vb.memory = "256"
			vb.cpus = 1
		end
	end
end
