"""empty message

Revision ID: be18e06eac11
Revises: c67338cde86e
Create Date: 2016-05-29 10:40:03.190888

"""

# revision identifiers, used by Alembic.
revision = 'be18e06eac11'
down_revision = 'c67338cde86e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idc', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idc', 'status',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
