"""empty message

Revision ID: c67338cde86e
Revises: 7029939d62d4
Create Date: 2016-05-29 10:13:44.705075

"""

# revision identifiers, used by Alembic.
revision = 'c67338cde86e'
down_revision = '7029939d62d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idc', sa.Column('status', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_idc_status'), 'idc', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idc_status'), table_name='idc')
    op.drop_column('idc', 'status')
    ### end Alembic commands ###
