"""empty message

Revision ID: d1ab73a1ed11
Revises: a0d3ab293918
Create Date: 2016-06-05 13:56:40.875341

"""

# revision identifiers, used by Alembic.
revision = 'd1ab73a1ed11'
down_revision = 'a0d3ab293918'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('ipinfo1', sa.String(length=250), nullable=True))
    op.drop_column('server', 'ipinfo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('ipinfo', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('server', 'ipinfo1')
    ### end Alembic commands ###
